select * from  rh_employe
select * from  rh_presence
SELECT 
         COALESCE(SUM(heures_calculees), 0) AS total_effectuees,
         COALESCE(SUM(CASE WHEN calcul_approuve = true THEN heures_payables ELSE 0 END), 0) AS total_approuvees
       FROM rh_presence 

BEGIN;

-- ==============================================================================
-- 1. PÉRIODES RH (rh_mois)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_mois (
    idmois          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence        INTEGER NOT NULL,
    mois            INTEGER NOT NULL,
    annee           INTEGER NOT NULL,
    libelle         VARCHAR(60) NOT NULL,
    date_debut      DATE NOT NULL,
    date_fin        DATE NOT NULL,
    cloture         BOOLEAN NOT NULL DEFAULT FALSE,
    date_cloture    TIMESTAMP NULL,
    cloture_par     INTEGER NULL,
    actif           BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_rh_mois UNIQUE (idagence, mois, annee),
    CONSTRAINT ck_rh_mois_valeur CHECK (mois BETWEEN 1 AND 12),
    CONSTRAINT ck_rh_mois_dates CHECK (date_fin >= date_debut)
);

-- ==============================================================================
-- 2. FICHE EMPLOYÉ COMPLÈTE (rh_employe)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_employe (
    idemploye                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,

    -- Identifiants & État civil
    code_employe                    VARCHAR(50) NOT NULL,
    matricule                       VARCHAR(50),
    nom                             VARCHAR(100) NOT NULL,
    prenom                          VARCHAR(150),
    nom_complet                     VARCHAR(255),
    sexe                            VARCHAR(10) DEFAULT 'M',
    date_naissance                  DATE,
    lieu_naissance                  VARCHAR(150),
    nationalite                     VARCHAR(100) DEFAULT 'Togolaise',

    -- Contacts & Adresse
    telephone                       VARCHAR(50),
    telephone2                      VARCHAR(50),
    email                           VARCHAR(150),
    adresse                         TEXT,
    ville                           VARCHAR(100),
    pays                            VARCHAR(100) DEFAULT 'Togo',

    -- Poste & Hiérarchie
    date_embauche                   DATE,
    date_sortie                     DATE,
    fonction                        VARCHAR(150),
    service                         VARCHAR(150),
    departement                     VARCHAR(150),
    poste                           VARCHAR(150),
    idsuperieur                     BIGINT NULL,
    type_contrat                    VARCHAR(50) DEFAULT 'CDI',
    statut_employe                  VARCHAR(30) NOT NULL DEFAULT 'ACTIF',

    -- Rémunération
    salaire_mensuel                 NUMERIC(18,2) NOT NULL DEFAULT 0,
    montant_heure                   NUMERIC(18,2) NOT NULL DEFAULT 0,
    heures_mensuelles_theoriques    NUMERIC(10,2) NOT NULL DEFAULT 0,

    -- Configuration Authentification & Pointage
    utiliser_qr                     BOOLEAN NOT NULL DEFAULT TRUE,
    utiliser_codebarre              BOOLEAN NOT NULL DEFAULT FALSE,
    utiliser_visage                 BOOLEAN NOT NULL DEFAULT FALSE,
    utiliser_signature              BOOLEAN NOT NULL DEFAULT FALSE,

    -- Données Multimédia & Signatures
    photo                           TEXT,          -- Chemin du fichier ou Base64
    codebarre                       VARCHAR(255),
    signature                       TEXT,          -- Chemin du fichier ou Base64
    qr_token                        VARCHAR(255),  -- Jeton unique généré pour le badge QR

    observation                     TEXT,
    actif                           BOOLEAN NOT NULL DEFAULT TRUE,

    -- Audit
    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modification               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    cree_par                        INTEGER,
    modifie_par                     INTEGER,

    CONSTRAINT uq_rh_employe_code UNIQUE (idagence, code_employe),
    CONSTRAINT ck_rh_employe_salaire CHECK (salaire_mensuel >= 0),
    CONSTRAINT ck_rh_employe_taux CHECK (montant_heure >= 0)
);

-- ==============================================================================
-- 3. AUTHENTIFICATION BIOMÉTRIQUE & QR (rh_employe_authentification)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_employe_authentification (
    idauth                          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    idemploye                       BIGINT NOT NULL,
    qr_code                         VARCHAR(255),
    face_template                   TEXT,         -- Embedding / Vecteur du visage
    face_template_version            VARCHAR(50),
    date_enregistrement_visage      TIMESTAMP,
    date_enregistrement_qr          TIMESTAMP,
    actif                           BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_rh_auth_emp FOREIGN KEY (idemploye) REFERENCES rh_employe(idemploye) ON DELETE CASCADE,
    CONSTRAINT uq_rh_auth_emp UNIQUE (idagence, idemploye)
);

-- ==============================================================================
-- 4. POINTAGE & PRÉSENCES (rh_presence)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_presence (
    idpresence                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    idemploye                       BIGINT NOT NULL,

    date                            DATE NOT NULL,
    idmois                          INTEGER NOT NULL,
    idannee                         INTEGER NOT NULL,

    -- Pointage Arrivée
    heure_arrivee                   TIMESTAMP NULL,
    methode_arrivee                 VARCHAR(30), -- 'QR', 'VISAGE', 'MANUEL'
    qr_arrivee_valide               BOOLEAN DEFAULT FALSE,
    visage_arrivee_valide           BOOLEAN DEFAULT FALSE,
    heure_arrivee_approuvee         BOOLEAN NOT NULL DEFAULT FALSE,
    arrivee_approuvee_par           INTEGER,
    arrivee_date_approbation        TIMESTAMP,
    arrivee_motif_rejet             TEXT,

    -- Pointage Départ
    heure_depart                    TIMESTAMP NULL,
    methode_depart                  VARCHAR(30),
    qr_depart_valide                BOOLEAN DEFAULT FALSE,
    visage_depart_valide            BOOLEAN DEFAULT FALSE,
    heure_depart_approuvee          BOOLEAN NOT NULL DEFAULT FALSE,
    depart_approuve_par             INTEGER,
    depart_date_approbation         TIMESTAMP,
    depart_motif_rejet              TEXT,

    -- Calcul & Validation Finale
    calcul_approuve                 BOOLEAN NOT NULL DEFAULT FALSE,
    calcul_approuve_par             INTEGER,
    date_calcul_approbation         TIMESTAMP,

    heures_calculees                NUMERIC(10,2) NOT NULL DEFAULT 0, -- Heures brutes travaillées
    heures_payables                 NUMERIC(10,2) NOT NULL DEFAULT 0, -- Heures validées pour la paie
    taux_horaire_applique           NUMERIC(18,2) NOT NULL DEFAULT 0,
    montant_calcule                 NUMERIC(18,2) NOT NULL DEFAULT 0,

    statut                          VARCHAR(30) NOT NULL DEFAULT 'INCOMPLETE', -- 'ARRIVEE', 'DEPART', 'COMPLETE', 'APPROUVE', 'REJETE'
    observation                     TEXT,

    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modification               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rh_pres_emp FOREIGN KEY (idemploye) REFERENCES rh_employe(idemploye),
    CONSTRAINT uq_rh_pres_jour UNIQUE (idagence, idemploye, date)
);

-- ==============================================================================
-- 5. DEMANDES DE PAIEMENT & AVANCES D'HEURES (rh_demande_paiement)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_demande_paiement (
    iddemande                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    idemploye                       BIGINT NOT NULL,

    date                            DATE NOT NULL,
    idmois                          INTEGER NOT NULL,
    idannee                         INTEGER NOT NULL,

    type_demande                    VARCHAR(30) NOT NULL, -- 'PAIEMENT_HEURES', 'AVANCE_HEURES'
    heures_demandees                NUMERIC(10,2) NOT NULL DEFAULT 0,
    taux_horaire                    NUMERIC(18,2) NOT NULL DEFAULT 0,
    montant_demande                 NUMERIC(18,2) NOT NULL DEFAULT 0,

    mode_paiement_souhaite          VARCHAR(30) NOT NULL DEFAULT 'TMONEY', -- 'ESPECES', 'TMONEY', 'COMPTE_BANCAIRE'
    numero_compte_ou_tel            VARCHAR(100),

    motif                           TEXT,
    statut                          VARCHAR(30) NOT NULL DEFAULT 'EN_ATTENTE', -- 'EN_ATTENTE', 'ACCORDEE', 'REJETEE', 'ANNULEE'

    -- Validation par le responsable
    approuve_par                    INTEGER,
    date_approbation                TIMESTAMP,
    raison_decision                 TEXT,

    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_modification               TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rh_dem_emp FOREIGN KEY (idemploye) REFERENCES rh_employe(idemploye),
    CONSTRAINT ck_rh_dem_type CHECK (type_demande IN ('PAIEMENT_HEURES', 'AVANCE_HEURES')),
    CONSTRAINT ck_rh_dem_statut CHECK (statut IN ('EN_ATTENTE', 'ACCORDEE', 'REJETEE', 'ANNULEE')),
    CONSTRAINT ck_rh_dem_mode CHECK (mode_paiement_souhaite IN ('ESPECES', 'TMONEY', 'COMPTE_BANCAIRE'))
);

-- ==============================================================================
-- 6. PAIEMENTS EFFECTUÉS (rh_paiement)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_paiement (
    idpaiement                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    iddemande                       BIGINT NOT NULL,
    idemploye                       BIGINT NOT NULL,

    date                            DATE NOT NULL,
    idmois                          INTEGER NOT NULL,
    idannee                         INTEGER NOT NULL,

    heures_payees                   NUMERIC(10,2) NOT NULL DEFAULT 0,
    taux_horaire                    NUMERIC(18,2) NOT NULL DEFAULT 0,
    montant                         NUMERIC(18,2) NOT NULL DEFAULT 0,

    mode_paiement                   VARCHAR(30) NOT NULL, -- 'ESPECES', 'TMONEY', 'COMPTE_BANCAIRE'
    numero_transaction              VARCHAR(150),
    banque                          VARCHAR(150),
    numero_compte                   VARCHAR(150),
    telephone_tmoney                VARCHAR(50),

    paye                            BOOLEAN NOT NULL DEFAULT TRUE,
    paye_par                        INTEGER,
    date_paiement                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    observation                     TEXT,
    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rh_paie_dem FOREIGN KEY (iddemande) REFERENCES rh_demande_paiement(iddemande),
    CONSTRAINT fk_rh_paie_emp FOREIGN KEY (idemploye) REFERENCES rh_employe(idemploye)
);

-- ==============================================================================
-- 7. CONFIRMATION DE RÉCEPTION DU PAIEMENT PAR L'EMPLOYÉ (rh_paiement_confirmation)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_paiement_confirmation (
    idconfirmation                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    idpaiement                      BIGINT NOT NULL,
    idemploye                       BIGINT NOT NULL,

    date                            DATE NOT NULL,
    idmois                          INTEGER NOT NULL,
    idannee                         INTEGER NOT NULL,

    confirme                        BOOLEAN NOT NULL DEFAULT FALSE,
    date_confirmation               TIMESTAMP,
    commentaire                     TEXT,
    signature_confirmation          TEXT,

    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rh_conf_paie FOREIGN KEY (idpaiement) REFERENCES rh_paiement(idpaiement),
    CONSTRAINT fk_rh_conf_emp FOREIGN KEY (idemploye) REFERENCES rh_employe(idemploye),
    CONSTRAINT uq_rh_conf_paie UNIQUE (idagence, idpaiement)
);

-- ==============================================================================
-- 8. MESSAGES & NOTIFICATIONS (rh_message)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_message (
    idmessage                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    idemploye                       BIGINT NOT NULL,

    date                            DATE NOT NULL,
    idmois                          INTEGER NOT NULL,
    idannee                         INTEGER NOT NULL,

    type_message                    VARCHAR(50), -- 'PAIEMENT_EFFECTUE', 'DEMANDE_STATUT', 'INFO'
    titre                           VARCHAR(255) NOT NULL,
    message                         TEXT NOT NULL,

    lu                              BOOLEAN NOT NULL DEFAULT FALSE,
    date_lecture                    TIMESTAMP,

    idpaiement                      BIGINT NULL,
    iddemande                       BIGINT NULL,

    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_rh_msg_emp FOREIGN KEY (idemploye) REFERENCES rh_employe(idemploye)
);

-- ==============================================================================
-- 9. HISTORIQUE D'AUDIT (rh_audit)
-- ==============================================================================
CREATE TABLE IF NOT EXISTS rh_audit (
    idaudit                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idagence                        INTEGER NOT NULL,
    date                            DATE NOT NULL,
    idmois                          INTEGER NOT NULL,
    idannee                         INTEGER NOT NULL,
    utilisateur                     INTEGER,
    table_name                      VARCHAR(100) NOT NULL,
    id_enregistrement               BIGINT,
    operation                       VARCHAR(20) NOT NULL,
    ancienne_valeur                 JSONB,
    nouvelle_valeur                 JSONB,
    adresse_ip                      VARCHAR(100),
    date_creation                   TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- ==============================================================================
-- INDEX D'OPTIMISATION
-- ==============================================================================
CREATE INDEX IF NOT EXISTS idx_rh_emp_ag_actif ON rh_employe(idagence, actif);
CREATE INDEX IF NOT EXISTS idx_rh_emp_qr ON rh_employe(idagence, qr_token);
CREATE INDEX IF NOT EXISTS idx_rh_pres_emp_date ON rh_presence(idagence, idemploye, date);
CREATE INDEX IF NOT EXISTS idx_rh_pres_mois ON rh_presence(idagence, idmois, idannee);
CREATE INDEX IF NOT EXISTS idx_rh_dem_emp_statut ON rh_demande_paiement(idagence, idemploye, statut);
CREATE INDEX IF NOT EXISTS idx_rh_paie_emp ON rh_paiement(idagence, idemploye);
CREATE INDEX IF NOT EXISTS idx_rh_msg_emp ON rh_message(idagence, idemploye, lu);

COMMIT;